name: codingsoft

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  codingsoft:
    if: |
      contains(github.event.comment.body, ' /cs') ||
      startsWith(github.event.comment.body, '/cs') ||
      contains(github.event.comment.body, ' /codingsoft') ||
      startsWith(github.event.comment.body, '/codingsoft')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run codingsoft
        uses: CodingSoft/codingsoft/github@latest
        env:
          CODINGSOFT_API_KEY: ${{ secrets.CODINGSOFT_API_KEY }}
          CODINGSOFT_PERMISSION: '{"bash": "deny"}'
        with:
          model: codingsoft/claude-opus-4-5
